### ISSUE TITLE
無法產生以下參數的地圖

### ISSUE THREAD

**Issue by clc168** [happyman/twmap#10]
Browser: Chrome,  Version 49.0.2623.87 (64-bit)
產生座標的參數
298
2788
A4R 14x10
台灣
經建三
包含山友gps trace + 彩圖

error: svg2png fail: Entity: line 35341: parser error : internal error: Huge input lookup+031 L 3107.445312 633.96875 L 3108.570312 633.164062 L 3108.757812 633.398438 "/+                                                                               ^+Entity: line 35342: parser error : Extra content at the end of the document+</g>+^+Entity: line 35341: parser error : internal error: Huge input lookup+031 L 3107.445312 633.96875 L 3108.570312 633.164062 L 3108.757812 633.398438 "/+                                                                               ^+Entity: line 35342: parser error : Extra content at the end of the document+</g>+^++*\* (inkscape:25223): WARNING **: Specified document /srv/www/htdocs/map/out/024226/298000x2788000-14x10-v3.svg2 cannot be opened (does not exist or not a valid SVG file)

**Comment by happyman** [comment]
原本先出底圖，再將 svg 合上的方法會有偏移。
改成讓 tilestache 去合，所以也不會有 svg 過多的問題了。tiles.inc.php
