### ISSUE TITLE
vector tile 實作

### ISSUE THREAD

**Issue by happyman** [happyman/twmap#11]
1. 是否能用 vector tile 來呈現 gps tracks?
2. 是否可以產生 offline track map 給手機使用?

**Comment by chihchun** [comment]
1. 理論上 GeoJSON/GPX 就是 vector layer.
2. 只要 mobile browser or app 可以 render GeoJSON or GPX or KML.

**Comment by happyman** [comment]
不過資料有點多, 兩萬多條 gpx 放在 postgis 裡面, 匯出來 geoJSON 有 1G 多.

**Comment by kcwu** [comment]
offline 的話, 可以考慮轉成 mapsforge format. 它用 binary encoding, 應該可以小很多.

**Comment by chihchun** [comment]
請問這些 gpx track 都是 unique path?

**Comment by happyman** [comment]
@kcwu 沒錯.  有無從 postgis table 轉成 .map 的指令範例? 好像都要透過 osmosis?  @chihchun: 熱門路線的話,不同隊,不同時間, 重複的很多.

**Comment by kcwu** [comment]
對, 要用 osmosis, 所以要先把那些 track 轉成 osm format. 我不知道有沒有現成 tool, 不過 gpx 沒什麼 attributes, 所以自己轉也不難. 有需要的話我可以幫忙.

**Comment by kcwu** [comment]
其中一種兜法: 
1. 把單一 gpx 轉成 osm: 可以用 gpsbabel
2. 把一堆 osm 檔接起來: 可以用 osmosis
3. 把接起來的 osm 檔轉成 .map: 用 mapsforge 的 osmosis mapwriter plugin

**Comment by happyman** [comment]
@kcwu 原始的 gpx 可能已經被使用者刪除, 變成只有 gdal ogr2ogr 轉進去 postgis 裡面的 table (trk 跟 wpt 分開兩張), 這樣有辦法轉回 osm 嘛?

**Comment by kcwu** [comment]
因為我們並不需要 trk 跟 wpt 的對應關係, 不用還原成原本的 gpx 檔, 所以沒問題.

**Comment by happyman** [comment]
@kcwu 轉成 osm 很慢又佔空間,有無直接從 shp 檔轉 mapsforge .map 的方法？

**Comment by kcwu** [comment]
有 http://wiki.openstreetmap.org/wiki/Shp2osm, 不知道合不合用

**Comment by happyman** [comment]
在 @kcwu 的幫忙下, 總算是將 pgsql 資料轉成 osm, 然後再轉成 .map 放入手機. 結果發現 oruxmaps 的 composite map 只能 online 配 online, offline 配 offline, 看起來沒什麼用.
我還是提供行跡 transparent 的 raster tile 好了.

**Comment by happyman** [comment]
50gray 先生還沒來: https://www.keepon.com.tw/thread-5a0f53ee-cad9-e511-80c1-901b0e54a4e6.html#comment-form 感覺是提供  gpx track 的 tile url 即可.

**Comment by happyman** [comment]
有 MOI_OSM 不用管這個了
