### ISSUE TITLE
加上台灣三家電信公司涵蓋率

### ISSUE THREAD

**Issue by happyman** [happyman/twmap#12]
使用者反應加上電信公司涵蓋率資料:
中華電信: http://www.emome.net/internet_coverage (http://221.120.19.26/coverage/tw.html)
台灣大哥大: https://www.taiwanmobile.com/mobile/calculate/cover_map.html
遠傳 :http://www.fetnet.net/service/roadtestresult/signal/cover_communica.html

初步看了一下都是用 Groundoverlay 去做的.
CHT: http://221.120.19.26/coverage/jss/mobile/mobileMap.js

有 voice, 3-3.5G, 4G 三個背景圖.

舉例: https://www.taiwanmobile.com/mobile/calculate/maps/4G/TW.png?r=20160816
資料(image url)還要整理, 官方的更新頻率未知. 
直接引用官方 image 不一定可行, 可能需要砍圖下來比較保險.

**Comment by happyman** [comment]
worldwide:  SpeedTest 或 OpenSignal.
台灣的輪子:
https://play.google.com/store/apps/details?id=com.shaojung.wildcall
https://play.google.com/store/apps/details?id=org.wildcall.dct

from: https://www.facebook.com/cplu434?fref=nf

**Comment by kcwu** [comment]
FYI, 
OpenSignal 名字有 open 但不夠 open
另一個類似的 service, http://opencellid.org/ 可以下載 raw data.

**Comment by chihchun** [comment]
比較可以利用的是 OpenCellID[4] 與 Mozilla Location Services[5]，社群有開發相關工具用來產生資料庫[6][7]。不過依照使用人數，數據可能不太即時與完整。

[4] OpenCellId http://opencellid.org
[5] Mozilla Location Services https://location.services.mozilla.com
[7] sobrus/FastLacellsGenerator: Fast lacells.db database generator script for LocalGSMBackend by n76 - https://github.com/sobrus/FastLacellsGenerator
[8] n76/lacells-creator: Script for generating a cell tower database for NetworkLocation from the microG project - https://github.com/n76/lacells-creator

**Comment by kcwu** [comment]
Mozilla location service 的問題是, 它提供的 service 是用來 "從收到的訊號計算所在地點", 但它本身不提供 raw data 或是 coverage 之類的資訊. 以我們的用途, 唯一可用的是他 https://location.services.mozilla.com/map 的 low resolution tile.

btw, 我之前有抓過 OpenCellID 的 raw data, 然後 extract 出台灣的部分. 如果有人有需要的話我可以提供, 省得重抓. 之前我也想過自製 coverage map, 不過抓完資料就沒繼續了 :P

**Comment by kcwu** [comment]
補充說明, chihchun 提到的資料庫是基地台位置, 但我想要知道的是在某處能不能收到訊號, 這是基地台資料庫無法提供的.

**Comment by chihchun** [comment]
現在 Mozilla Location Service 匯出的格式[1]跟 OpenCellID 一樣了。

MLS/OpenCellID 應該是都是蒐集人收到資料的訊號強度，不是基地台的實體位置。
理論上在山中應該都會是走在步道上蒐集資料。

[1] MLS - Downloads - https://location.services.mozilla.com/downloads

Kuang-che Wu <notifications@github.com> 於 2016年8月29日 下午8:28 寫道：

**Comment by kcwu** [comment]
不一樣. Mozilla Location Service 匯出的是觀測到的 cell station data, 但沒有 "從何處觀測到" 的資訊。 那個座標也許是 cell station 自己報的, 或是根據 sensor data 推算出來的, 我沒有仔細研究。

chihchun 給的 download page 最下面這段就有說明為何 mozilla 不提供蒐集者的座標.
```
In addition to the aggregate network data, the service also gathers the raw observation data these aggregates are based on. While we do not store any individual user token with the observation data, the data itself contains plenty of unique characteristics, locations and timestamps that would allow someone to track the movements of the people contributing observations to this service.

We have therefor chosen to use a conservative approach and do not make the raw observation data public. In the future we might consider an additional explicit user opt-in, to let users signal their willingness to have their observation data published, as long as we can make the possible risk clear to them.
```

**Comment by happyman** [comment]
1. 取 4G 就好, 3G 跟語音都慢慢少用.
2. 中國福建省,澎湖先不管.

cht: http://221.120.19.26/coverage/images/mobile/4g_tw.png

"ulat":25.554136 ,
"ulon":124.434457584427,
"llat":21.635736302326,
"llon":115.760122946358

http://221.120.19.26/coverage/jss/mobile/mEmbr.json

台哥大:
4G tw: https://www.taiwanmobile.com/mobile/calculate/maps/4G/TW.png?r=20160816

var srcImage1 = '/mobile/calculate/maps/4G/TW.png?r=20160816';
var swBound1 = new google.maps.LatLng(21.85034169135, 119.267143584823);
var neBound1 = new google.maps.LatLng(25.342129534416, 122.116226971802);
var bounds1 = new google.maps.LatLngBounds(swBound1, neBound1);
overlay1 = new google.maps.GroundOverlay(srcImage1,bounds1);
overlay1.setMap(googleMap);

遠傳:
http://www.fetnet.net/service/roadtestresult/signal/img/coverage4G.png
bound: new google.maps.LatLng(19.921522519575,114.523552468047),
  new google.maps.LatLng(27.109534289724,127.141960219481));

整理如下:
```
var cover_overlay;
var coverage = {"cht":{"bound":{"north":25.554136,"south":21.635736302326,"east":124.43445758443,"west":115.76012294636},"img":"http:\/\/221.120.19.26\/coverage\/images\/mobile\/4g_tw.png"},"twn":{"bound":{"north":25.342129534416,"south":21.85034169135,"west":119.26714358482,"east":122.1162269718},"img":"https:\/\/www.taiwanmobile.com\/mobile\/calculate\/maps\/4G\/TW.png?r=2016081"},"fet":{"bound":{"north":27.109534289724,"south":19.921522519575,"west":114.52355246805,"east":127.14196021948},"img":"http:\/\/www.fetnet.net\/service\/roadtestresult\/signal\/img\/coverage4G.png"}};

function coverage_overlay(op, action ) {

if (typeof coverage_overlay.setMap !== 'undefined') {
     cover_overlay.setMap(null);
}
if (action == 1) {
     cover_overlay = new google.maps.GroundOverlay(coverage[op].img, coverage[op].bound, {      opacity:0.7  } );
     cover_overlay.setMap(map);
}
}
```

先不做介面.
使用就按下 f12, 然後打 coverage_overlay('cht',1); 或者 coverage_overlay('twn',1); 或者 coverage_overlay('fet',1)

由於使用者原意是想要知道可能通訊點, 但是上述的圖其實在山區用途不大(深山幾乎空白,但實測上可能可通語音).
不如把可熱門山徑的可通訊點做成 kml 疊加, 然後當作行程規劃參考.

**Comment by happyman** [comment]
727b691  v4.01 上線
