### ISSUE TITLE
整合 Rudy 的 MOI_OSM 地圖

### ISSUE THREAD

**Issue by happyman** [happyman/twmap#16]
https://www.facebook.com/groups/taiwan.topo/

# MOI.OSM - Taiwan TOPO v2016.11.03 發行
好消息，Taiwan TOPO Mapsforge (Android) 地圖正式開始發行。
https://dl.dropboxusercontent.com/u/8997…/…/taiwan_topo.html

Happyman: Rudy Chung 感謝你的成果。因為我對非山區實在沒興趣, 我可以拿你的 maps 做基礎, 去產生地圖產生器想要的圖資嗎?
Rudy Chung:  可以呀，非常歡迎。若需要協助，請跟我說，謝謝！  🗡 

plan
1. 將 OSM 置換成 MOI_OSM 
2. 在 MOI_OSM 上疊合 gpx layer 當前景圖取代經建一版.
3. 出 MOI_OSM 的圖??

**Comment by happyman** [comment]
1. update as f60088f

**Comment by chihchun** [comment]
疑，這是只有等高線，但是不用 OSM 的路線資料？

**Comment by happyman** [comment]
@chihchun  我只改 zoom > 13 的 wood mask 部分, 其他 theme rules 都沒動.

**Comment by alpha-rudy** [comment]
呵呵，與有榮焉！  :D

**Comment by happyman** [comment]
https://www.facebook.com/groups/taiwan.topo/permalink/874934549328826/ 改名 XD

**Comment by happyman** [comment]
@alpha-rudy   fyi
https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md

![image](https://user-images.githubusercontent.com/82296/31345385-241f3d3c-ad48-11e7-8b02-123743324921.png)

xxd -c 40 -l 105 -s 80    ~/mapsforge/20170601/MOI_OSM_Taiwan_TOPO_Rudy.map 
from byte 80 length 105 byte comment can identify Rudy's map version

**Comment by happyman** [comment]
Daily Drops 的路徑如下：
* index.json:
  http://rudy.basecamp.tw/drops/index.json
* map file:
  http://rudy.basecamp.tw/drops/MOI_OSM_Taiwan_TOPO_Rudy.map.zip
* twmap style:
  http://rudy.basecamp.tw/drops/MOI_OSM_twmap_style.zip
另，KC Wu 兄的連結如下：
* index.json:
  http://moi.kcwu.csie.org/drops/index.json
* map file:
  http://moi.kcwu.csie.org/drops/MOI_OSM_Taiwan_TOPO_Rudy.map.zip
* twmap style:
  http://moi.kcwu.csie.org/drops/MOI_OSM_twmap_style.zip

Weekly Release 只要把 URL 的 /drops 移除就好。
另有一點，我發現，Rex 兄的 CDN 常常會 out-dated，可能得注意一下。
我都用這個 check-mirror.py 來檢查 mirror 的情況，Happyman 兄可以參考一下。
謝謝！  ^^
=-=-=-=-
有這個就可以比對版本了。

**Comment by alpha-rudy** [comment]
嗨， @happyman ，

透過 jq 很快就可以知道版號喔！

    $ cat index.json | jq '.[] | select(.name == "MOI_OSM_twmap_style.zip") | .version'
    "v2017.09.27"

Thanks,
Rudy  10/11

**Comment by happyman** [comment]
謝謝 @alpha-rudy

**Comment by happyman** [comment]
https://www.facebook.com/groups/taiwan.topo/permalink/984650191690594/  輸出魯地圖有字太小的問題

**Comment by alpha-rudy** [comment]
Got it, @happyman ！  ^^

**Comment by happyman** [comment]
https://www.facebook.com/groups/taiwan.topo/permalink/991879704300976/
三角點 feature 打開並且更新 
![image](https://user-images.githubusercontent.com/82296/39849439-eefea8ec-543e-11e8-8e58-ff5e744f8694.png)

**Comment by happyman** [comment]
整合 Rudy_BN style: @alpha-rudy  default 值能全開嗎?
```
   <layer id="elmt-surveypoint-c" enabled="false">
      <name lang="en" value="survey point"/>
      <name lang="zh" value="標石 (基點)"/>
      <cat id="surveypoint"/>
    </layer>
    <layer id="elmt-h_acc_no-c" enabled="false">
      <name lang="en" value="Inaccess pathway"/>
      <name lang="zh" value="封閉路線"/>
      <cat id="h_acc_no"/>
    </layer>
    <layer id="elmt-hiking" visible="true">
      <name lang="en" value="Hiking v2018.10.04"/>
      <name lang="zh" value="登山 v2018.10.04"/>
      <overlay id="elmt-contour-c"/>
      <overlay id="elmt-peak-c"/>
      <overlay id="elmt-surveypoint-c"/>
      <overlay id="elmt-trail-c"/>
      <overlay id="elmt-h_routes-c"/>
      <overlay id="elmt-h_acc_no-c"/>
    </layer>
```

**Comment by chihchun** [comment]
> 嗨，召喚 @chihchun 兄！ 
> 這些 overlay 雖然 style file 上有 default 值，但是 APP 都可以由使用者來各自選定與更改。 
> Rex 兄，請問你知道圖磚伺服器是否有類似的設定可以來把這些 overlay 都打開嗎？ ^^

mapsforge engine 可以讀取配置檔[1]，配置檔副檔名是 .prop. 我自己的伺服器有手動修改過幾個圖層。

@happyman  應該已經可以透過他的自己寫的 rendering server 修改配置了。有需要的話，我可以把我的程式碼再整理一下以及 docker image 分享出來。

[1] https://svn.code.sf.net/p/mobac/code/trunk/tools/MapsforgeSrv/src/MapsforgeHandler.java
