### ISSUE TITLE
oruxmaps kml 轉換後的 gpx 無法上傳到 osm

### ISSUE THREAD

**Issue by happyman** [happyman/twmap#17]
50gray report: https://www.keepon.com.tw/thread-4bd4673f-2e99-e611-80c4-901b0e54a4e6.html
將您提供的GPX檔案匯進OSM套圖時，不被接受，會被刪除消失。
你看到的畫面是緩衝時間載入OSM編輯模式才能看到，超過60秒後就會自動消失了。
之前您提供GPX軌跡檔匯入OSM內都有類似問題。

初步查是 gpsbabel 傳換 oruxmaps 的 kml -> gpx 之後 timestamp 消失

**Comment by chihchun** [comment]
並非無 timestamp 的緣故，官方的 GPX track 上傳機制也容許刪去 timestamp 等容易洩漏個人隱私的資訊。

在 iD 1.9.7[1] 下測試原檔沒問題，直接下載的 GPX 檔案可以正常載入沒問題。但是由於原始 GPX 裡面帶入了四張照片，GPX 大小高達 1.4M，以至於 iD 運作十分緩慢。如果用 Viking[2] 編輯，刪去這四張照片紀錄後，檔案大小只需要 83K，網頁編輯器速度也快許多。可能是因為瀏覽器緣故造成軌跡消失，建議改用編輯功能強大的 josm[3]。

至於 GPX 嵌入照片的作法，官方規格[4]應該是使用 linkType[5]，使用網址指到照片位置。但是實務上有個各種不同的實做，像是蚯蚓貼出來的用 base64 內嵌照片給網頁使用的版本，以及 om:oruxmapsextensions 的自訂 xml tag 版本，以至於相容性不佳。
<wpt>
<link href="http://somewhere">
	<text>foobar</text>
</link>
</wpt>

另外 Rudy Chung 使用 OSM 搭配內政部數位地形模式資料產製 Garmin 與 Mapsforge 格式圖資，每週更新一次[6][7]，不彷利用。

[1] https://github.com/openstreetmap/iD
[2] https://viking-gps.github.io/
[3] https://josm.openstreetmap.de/
[4] GPX: the GPS Exchange Format - http://www.topografix.com/gpx.asp
[5] GPX 1.1 Schema Documentation - http://www.topografix.com/gpx/1/1/#type_linkType
[6] http://rudy.basecamp.tw
[7] https://www.facebook.com/groups/taiwan.topo

**Comment by happyman** [comment]
謝謝 Rex 解惑。我看了一下 oruxmaps 輸出的 kmz/kml 還是含有 timestamp 但是採用下列方式:
https://developers.google.com/kml/documentation/kmlreference?csw=1#gxtrack 
但是經由 gpsbabel / ogr2ogr 轉換都不會保留。

photo wpt 使用 url link 的缺點是, 如果只下載 kml / gpx 其實只下載一半, 遠端的 url 消失則資訊遺失.
所以當時才決定 embed 照片在檔案裏面。(好像回到 netnews 傳照片的時代)

原始問題應該是將 photo wpt 刪除即可編輯。我這邊下次注意 export gpx 的時候要用 ogr2ogr -f GPX -dsco GPX_USE_EXTENSIONS=NO out.gpx in.kml 即可。
