### ISSUE TITLE
有關debug圖層

### ISSUE THREAD

**Issue by typebrook** [happyman/twmap#44]
@happyman 
建議可以直接使用Google Chart API，一來格式調整方便，二來可以省點自己host tile的資源：

- 範例一
  - 格式<br>https://chart.apis.google.com/chart?chst=d_text_outline&chs=256x256&chf=bg,s,00000044&chld=FFFFFF|32|h|000000|b|||x={x}|y={y}|z={z}||||______________
  - 成果<br>![](https://chart.apis.google.com/chart?chst=d_text_outline&chs=256x256&chf=bg,s,00000044&chld=FFFFFF|32|h|000000|b|||x=27430|y=14142|z=15||||______________)

- 範例二
  - 格式<br>https://chart.apis.google.com/chart?chst=d_text_outline&chs=512x512&chf=bg,s,00000044&chld=FFFFFF|32|h|000000|b|||||Google:%20%20({x},{y})|TMS:%20%20({x},{ty})|Zoom%20{z}||||||____________________________
  - 成果<br>![](https://chart.apis.google.com/chart?chst=d_text_outline&chs=512x512&chf=bg,s,00000044&chld=FFFFFF|32|h|000000|b|||||Google:%20%20(14,13)|TMS:%20%20(14,18)|Zoom%205||||||____________________________)

**Comment by happyman** [comment]
https://developers.google.com/chart/image/docs/chart_params 這個 api  is deprecated in 2012 and was turned off on March 18, 2019。另外似乎沒有辦法加上邊框?

**Comment by typebrook** [comment]
下線講好久了，但一直都可以用XD

>另外似乎沒有辦法加上邊框?

不確定是否可以，但可以用交互的方式改變背景顏色：
![Screenshot from 2019-12-23 18-00-12](https://user-images.githubusercontent.com/19887090/71351256-2c89ff80-25ae-11ea-905c-507569ce69a9.png)

source: https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/

不過這個顯示tile編號的方法只是建議啦，若寫個script不花什麼心力，還是用自己習慣的方式會比較好

**Comment by happyman** [comment]
這樣做不用花甚麼力氣~ 謝嚕
$cmd = sprintf("convert -size 256x256 xc:White \
  -pointsize 40 \
  -fill white \
  -stroke navy  -strokewidth 1 \
  -gravity Center \
  -annotate 0  \"%s\" \
  -bordercolor red    -border 1x1 \
  png:-",pg_escape_string($string));
