### ISSUE TITLE
twmap3 「歡迎光臨」頁加連結到此 GitHub.

### ISSUE THREAD

**Issue by jidanni** [happyman/twmap#51]
建議於 https://map.happyman.idv.tw/~mountain/twmap3/ 之「歡迎光臨」頁，
加連結到此 GitHub.
（但該頁非在本 GitHub, 所以我無法作 pull request.）

**Comment by jidanni** [comment]
https://map.happyman.idv.tw/twmap/main.php#_=_ 也缺連結到此 GitHub.

**Comment by kcwu** [comment]
@happyman

**Comment by happyman** [comment]
https://github.com/happyman/twmap/blob/master/twmap3/about.php
麻煩一下嚕~~

**Comment by happyman** [comment]
as #52 先用健行筆記頂著。

**Comment by happyman** [comment]
as #52 先用健行筆記頂著。
