### ISSUE TITLE
無聯絡資料

### ISSUE THREAD

**Issue by jidanni** [happyman/twmap#54]
https://map.happyman.idv.tw/~happyman
https://happyman.idv.tw/
等等無聯絡資料。
萬一發現問題無法反映。

**Comment by happyman** [comment]
謝嚕~ 
![image](https://user-images.githubusercontent.com/82296/112598666-df987700-8e49-11eb-989b-893965e9739f.png)
also 
https://www.facebook.com/twmapgen
