### ISSUE TITLE
extend Coverage layer with APTG/TStar 

### ISSUE THREAD

**Issue by festivalfl** [happyman/twmap#59]
following [#12](https://github.com/happyman/twmap/issues/12), [#31](https://github.com/happyman/twmap/issues/31),[#58](https://github.com/happyman/twmap/issues/58)

lower freq with long coverage for mountain area

could we extend APTG/TStar Coverage layer (4G 700 / 900 MHz)?

APTG https://www.aptg.com.tw/others/Coverage.htm
TStar https://www.tstartel.com/CWS/serviceCoverage.php

Ref.
https://www.mobile01.com/topicdetail.php?f=18&t=5441521

freq bands
https://attach.mobile01.com/attach/201905/mobile01-b991f09473a9a664736a449cb14ac47f.jpg

netmonster app (for field trial by mobile device, android only)
- https://play.google.com/store/apps/details?id=cz.mroczis.netmonster
- [how to use app](https://www.youtube.com/watch?v=cGYbjZenM54)

**Comment by happyman** [comment]
台灣之星 4+5G
![image](https://user-images.githubusercontent.com/82296/145960085-e9fbb554-d908-4d50-816c-7104dcfc466d.png)
3G 
![image](https://user-images.githubusercontent.com/82296/145960191-3dba6212-e378-4eb2-87bf-713271a5e3f9.png)
亞太5G
![image](https://user-images.githubusercontent.com/82296/145960320-4da7a499-c53c-440f-ac59-2682773cd3cf.png)
這幾個看起來可以套，但是還得花時間研究。能直接幫我 patch 嗎?

**Comment by festivalfl** [comment]
先備忘一下... 我也還不知道怎轉連結介接
@typebrook 大大有時間幫個忙嗎?

![image](https://user-images.githubusercontent.com/26714354/145967922-9b38c537-1c55-4ba4-bd80-a811f5be78d5.png)
![image](https://user-images.githubusercontent.com/26714354/145967978-b1026b1e-4fd3-4ecf-adac-b3e9e26a93ff.png)

**Comment by typebrook** [comment]
@happyman 
好喔，晚上我來看看

**Comment by typebrook** [comment]
嗯...台灣之星不知道是怎麼切boundary的，這樣寫死的話我也沒辦法了：
![Screenshot from 2021-12-14 23-02-43](https://user-images.githubusercontent.com/19887090/146023891-db579864-3abf-4e4e-870a-ef6f06c227ad.png)
```javascript
    imageSrc = 'https://www.tstartel.com/static/coverage5G/',
    prefix_4G_L1 = 'TSTAR_L1_',
    prefix_4G_L2 = 'TSTAR_L2_',
    prefix_3G_L1 = '3G_TSTAR_L1_',
    prefix_3G_L2 = '3G_TSTAR_L2_',
    L1_Pic_Name, L2_Pic_Name,

...

    for (var k = 0; k < sp_lng * sp_lat + 3; k++) {

        var imgSrc = imageSrc + L1_Pic_Name + k + ".png";

        signalOverlayL1[k] = new google.maps.GroundOverlay(
            imgSrc,
            boundsL1[k],
            overlayOpts);
        signalOverlayL1[k].setMap(map);
    }
```

**Comment by typebrook** [comment]
至於亞太比較簡單，原始資料只是一個簡單的kml，包含了三張圖片和對應的bbox：
https://www.aptg.com.tw/coverage1/MOCN202107.kml
```kml
<?xml version="1.0" encoding="utf-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
<Folder>
<GroundOverlay>
<name>N_MOCN202107</name><visibility>1</visibility><Icon><href>https://www.aptg.com.tw/coverage1/N_MOCN202107.png</href></Icon><LatLonBox><north>25.319524</north><south>24.118276</south><east>122.36755</east><west>119.39645</west><rotation>0</rotation></LatLonBox>
</GroundOverlay>
<GroundOverlay>
<name>M_MOCN202107</name><visibility>1</visibility><Icon><href>https://www.aptg.com.tw/coverage1/M_MOCN202107.png</href></Icon><LatLonBox><north>24.149725</north><south>22.948875</south><east>121.681535</east><west>118.738465</west><rotation>0</rotation></LatLonBox>
</GroundOverlay>
<GroundOverlay>
<name>S_MOCN202107</name><visibility>1</visibility><Icon><href>https://www.aptg.com.tw/coverage1/S_MOCN202107.png</href></Icon><LatLonBox><north>23.039725</north><south>21.838875</south><east>121.966486</east><west>119.047514</west><rotation>0</rotation></LatLonBox>
</GroundOverlay>
<GroundOverlay>
<name>KM_MOCN202107</name><visibility>1</visibility><Icon><href>https://www.aptg.com.tw/coverage1/KM_MOCN202107.png</href></Icon><LatLonBox><north>24.922454</north><south>23.924146</south><east>119.45467</east><west>116.99133</west><rotation>0</rotation></LatLonBox>
</GroundOverlay>
<GroundOverlay>
<name>LJ_MOCN202107</name><visibility>1</visibility><Icon><href>https://www.aptg.com.tw/coverage1/LJ_MOCN202107.png</href></Icon><LatLonBox><north>26.805656</north><south>25.804944</south><east>121.229013</east><west>118.720987</west><rotation>0</rotation></LatLonBox>
</GroundOverlay>
</Folder>
</kml>
```

@happyman 我對google map api不熟，不過我猜你可以處理這個？

**Comment by happyman** [comment]
> 至於亞太比較簡單，原始資料只是一個簡單的kml，包含了五張圖片和對應的bbox： https://www.aptg.com.tw/coverage1/MOCN202107.kml
> 
> ```
> <kml xmlns="http://earth.google.com/kml/2.0">
>   <Folder>
>     <GroundOverlay>
>       <name>N_MOCN202107</name>
>       <visibility>1</visibility>
>       <Icon>
>         <href>https://www.aptg.com.tw/coverage1/N_MOCN202107.png</href>
>       </Icon>
>       <LatLonBox>
>         <north>25.319524</north>
>         <south>24.118276</south>
>         <east>122.36755</east>
>         <west>119.39645</west>
>         <rotation>0</rotation>
>       </LatLonBox>
>     </GroundOverlay>
>     <GroundOverlay>
>       <name>M_MOCN202107</name>
>       <visibility>1</visibility>
>       <Icon>
>         <href>https://www.aptg.com.tw/coverage1/M_MOCN202107.png</href>
>       </Icon>
>       <LatLonBox>
>         <north>24.149725</north>
>         <south>22.948875</south>
>         <east>121.681535</east>
>         <west>118.738465</west>
>         <rotation>0</rotation>
>       </LatLonBox>
>     </GroundOverlay>
>     <GroundOverlay>
>       <name>S_MOCN202107</name>
>       <visibility>1</visibility>
>       <Icon>
>         <href>https://www.aptg.com.tw/coverage1/S_MOCN202107.png</href>
>       </Icon>
>       <LatLonBox>
>         <north>23.039725</north>
>         <south>21.838875</south>
>         <east>121.966486</east>
>         <west>119.047514</west>
>         <rotation>0</rotation>
>       </LatLonBox>
>     </GroundOverlay>
>     <GroundOverlay>
>       <name>KM_MOCN202107</name>
>       <visibility>1</visibility>
>       <Icon>
>         <href>https://www.aptg.com.tw/coverage1/KM_MOCN202107.png</href>
>       </Icon>
>       <LatLonBox>
>         <north>24.922454</north>
>         <south>23.924146</south>
>         <east>119.45467</east>
>         <west>116.99133</west>
>         <rotation>0</rotation>
>       </LatLonBox>
>     </GroundOverlay>
>     <GroundOverlay>
>       <name>LJ_MOCN202107</name>
>       <visibility>1</visibility>
>       <Icon>
>         <href>https://www.aptg.com.tw/coverage1/LJ_MOCN202107.png</href>
>       </Icon>
>       <LatLonBox>
>         <north>26.805656</north>
>         <south>25.804944</south>
>         <east>121.229013</east>
>         <west>118.720987</west>
>         <rotation>0</rotation>
>       </LatLonBox>
>     </GroundOverlay>
>   </Folder>
> </kml>
> ```
> 
> @happyman 我對google map api不熟，不過我猜你可以處理這個？

亞太的應該沒問題。
台灣之星把圖層切tile，依據不同zoom去顯示，效能不錯，不過要套用有點麻煩。
我所知道前幾家在山區有自建或共構骨幹光纜，但台灣之星應該沒有，可忽略嗎?

**Comment by festivalfl** [comment]
很棒啊~ 亞太加上去至少 一類電信 裡面就有 4/5 => 80%的官方資訊可以疊了
台灣之星~我有空或有辦法就在找人一起努力試試如何patch
感謝大大

**Comment by happyman** [comment]
![image](https://user-images.githubusercontent.com/82296/146575023-3bda6afe-d5d6-4efc-8cde-e9395d7f84c6.png)
先看看這樣可不可以。

**Comment by festivalfl** [comment]
感謝大大~~ 對照亞太官網~目前介接的圖層名稱應該是 "5G NR+4G"
![GT5G](https://user-images.githubusercontent.com/26714354/146591247-b9819d32-c9c6-4590-98b4-4d9c1557f036.jpg)

**Comment by happyman** [comment]
> 感謝大大~~ 對照亞太官網~目前介接的圖層名稱應該是 "5G NR+4G" 
OK.  比照其他電信，都是 4+5G 好了。

**Comment by festivalfl** [comment]
Verified
感謝大大熱情相助，很棒，超感謝

![Screenshot_20211220-180542](https://user-images.githubusercontent.com/26714354/146752583-8af87948-1a89-4db8-b171-6bac20b72258.png)

**Comment by happyman** [comment]
謝謝光臨~
