### ISSUE TITLE
遠傳的4+5G訊號涵蓋與遠傳官網的不一樣

### ISSUE THREAD

**Issue by yeh928** [happyman/twmap#62]
最近在查詢武陵農場 雪東線 附近的訊號涵蓋，發現地圖瀏覽器上的 遠傳4+5G訊號涵蓋 比遠傳官網的少非常多 
(3G正常，與遠傳官網的UMTS相同)

地圖瀏覽器上的遠傳4+5G
https://imgur.com/jUqaosh

遠傳官網上的4+5G
https://imgur.com/l2WKoYz

**Comment by happyman** [comment]
![image](https://user-images.githubusercontent.com/82296/191445788-465f206b-d8d7-4367-adb5-36181261b024.png)
沒錯偏移了。

**Comment by happyman** [comment]
@yeh928 已修正。相關 ticket #58。
![image](https://user-images.githubusercontent.com/82296/191446743-af771d16-5d25-4e2d-8a0f-e1dfe499b32d.png)
